# Generated by Django 5.2.2 on 2026-04-22 11:48

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_number', models.CharField(help_text='8-digit UWA staff number', max_length=8, unique=True)),
                ('role', models.CharField(choices=[('ACADEMIC', 'Academic Staff'), ('HOD', 'Head of Department'), ('SCHOOL_OPS', 'School Operations'), ('HOS', 'Head of School')], max_length=20)),
                ('fte', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CASUAL', 'Casual')], default='FULL_TIME', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_members', to='api.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_department', to='api.staff'),
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('config_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('config_value', models.CharField(max_length=255)),
                ('value_type', models.CharField(choices=[('INT', 'Integer'), ('FLOAT', 'Float'), ('STR', 'String'), ('BOOL', 'Boolean')], default='STR', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.staff')),
            ],
            options={
                'db_table': 'system_configs',
            },
        ),
        migrations.CreateModel(
            name='WorkloadReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.IntegerField()),
                ('semester', models.CharField(choices=[('S1', 'Semester 1'), ('S2', 'Semester 2'), ('FULL_YEAR', 'Full Year')], max_length=10)),
                ('snapshot_fte', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIONED', 'Actioned')], default='PENDING', max_length=20)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('import_batch_id', models.UUIDField(default=uuid.uuid4)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historical_reports', to='api.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_reports', to='api.staff')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='api.workloadreport')),
            ],
            options={
                'db_table': 'workload_reports',
            },
        ),
        migrations.CreateModel(
            name='WorkloadItem',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('TEACHING', 'Teaching'), ('SERVICE', 'Service'), ('ASSIGNED_ROLE', 'Assigned Role'), ('HDR_SUPERVISION', 'HDR Supervision')], max_length=20)),
                ('unit_code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('allocated_hours', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.workloadreport')),
            ],
            options={
                'db_table': 'workload_items',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('IMPORTED', 'Imported from Excel'), ('MODIFIED_BY_REIMPORT', 'Modified by Re-import'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('COMMENT', 'Added Comment'), ('CONFIG_CHANGE', 'System Config Changed')], max_length=25)),
                ('comment', models.TextField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='api.staff')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='api.workloadreport')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['department', 'role'], name='staff_departm_99ca21_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['staff_number'], name='staff_staff_n_8a8c46_idx'),
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['is_active'], name='staff_is_acti_e9a75c_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='departments_name_c59a45_idx'),
        ),
        migrations.AddIndex(
            model_name='workloadreport',
            index=models.Index(fields=['status'], name='workload_re_status_4e6b91_idx'),
        ),
        migrations.AddIndex(
            model_name='workloadreport',
            index=models.Index(fields=['is_anomaly'], name='workload_re_is_anom_a5b0d8_idx'),
        ),
        migrations.AddIndex(
            model_name='workloadreport',
            index=models.Index(fields=['academic_year', 'semester'], name='workload_re_academi_8dfff2_idx'),
        ),
        migrations.AddIndex(
            model_name='workloadreport',
            index=models.Index(fields=['import_batch_id'], name='workload_re_import__f82743_idx'),
        ),
        migrations.AddIndex(
            model_name='workloadreport',
            index=models.Index(fields=['is_current'], name='workload_re_is_curr_6476fd_idx'),
        ),
        migrations.AddIndex(
            model_name='workloaditem',
            index=models.Index(fields=['report', 'category'], name='workload_it_report__7d669d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['report', '-created_at'], name='audit_logs_report__a67a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_by', '-created_at'], name='audit_logs_action__79bb20_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', '-created_at'], name='audit_logs_action__a429dc_idx'),
        ),
    ]
