# Generated by Django 5.2.2 on 2026-04-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_number',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
