# Generated by Django 5.2.2 on 2026-03-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workload'),
    ]

    operations = [
        migrations.AddField(
            model_name='workload',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='workload',
            name='is_sent',
            field=models.BooleanField(default=True),
        ),
    ]
