# Generated by Codex on 2026-05-04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_staff_staff_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('token_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('code_hash', models.CharField(max_length=64)),
                ('salt', models.CharField(max_length=32)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otp_tokens',
            },
        ),
        migrations.AddIndex(
            model_name='otptoken',
            index=models.Index(fields=['email', 'created_at'], name='otp_tokens_email_7214a4_idx'),
        ),
        migrations.AddIndex(
            model_name='otptoken',
            index=models.Index(fields=['expires_at'], name='otp_tokens_expires_149618_idx'),
        ),
    ]
