# Generated by Django 5.2.2 on 2026-05-02 07:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_staff_staff_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadreport',
            name='target_band',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workloadreport',
            name='target_teaching_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('IMPORTED', 'Imported from Excel'), ('MODIFIED_BY_REIMPORT', 'Modified by Re-import'), ('IMPORT_SKIP', 'Skipped by Re-import (protected)'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('CONFIRMATION', 'Confirmed by Academic'), ('SUBMIT_REQUEST', 'Approval Request Submitted'), ('WORKLOAD_EDIT', 'Staff Metadata Edited by HOD'), ('PROFILE_EDIT', 'Staff Metadata Edited by School Ops'), ('COMMENT', 'Added Comment'), ('CONFIG_CHANGE', 'System Config Changed')], max_length=25),
        ),
        migrations.AlterField(
            model_name='workloadreport',
            name='status',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='INITIAL', max_length=20),
        ),
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('token_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('code_hash', models.CharField(max_length=64)),
                ('salt', models.CharField(default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'otp_tokens',
                'indexes': [models.Index(fields=['email', 'expires_at'], name='otp_tokens_email_b554cf_idx')],
            },
        ),
    ]
