# Generated by Django 5.2.2 on 2026-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_workloadreport_target_band_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workloadreport',
            name='status',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='INITIAL', max_length=20),
        ),
    ]
