# Generated by Django 5.2.2 on 2026-03-30 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_workload_full_name_workload_is_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], max_length=20)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Supervisor Review'), ('approved', 'Approved by Supervisor'), ('rejected', 'Rejected by Supervisor')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.workload')),
            ],
        ),
    ]
