# Generated by Django 5.2.13 on 2026-05-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_workloadreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadreport',
            name='target_band',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workloadreport',
            name='target_teaching_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
