# Generated by Django 5.2.2 on 2026-03-30 12:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workload',
            index=models.Index(fields=['user', 'status'], name='api_workloa_user_id_a265a9_idx'),
        ),
    ]
