# Generated by Django 5.2.13 on 2026-05-03 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_workloadreport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRoleAssignment',
            fields=[
                ('assignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_code', models.CharField(choices=[('HoD', 'HoD'), ('Admin', 'Admin')], max_length=20)),
                ('department_scope', models.CharField(max_length=150)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'active'), ('disabled', 'disabled')], default='active', max_length=20)),
                ('disable_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_department', models.ForeignKey(blank=True, help_text='Populated when department_scope matches an existing Department.name', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='api.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='api.staff')),
            ],
            options={
                'db_table': 'staff_role_assignments',
                'indexes': [models.Index(fields=['staff', 'status'], name='staff_role__staff_i_b0461a_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkloadDistributionJob',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('academic_year', models.PositiveIntegerField()),
                ('semester', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_jobs', to='api.staff')),
            ],
            options={
                'db_table': 'workload_distribution_jobs',
                'indexes': [models.Index(fields=['academic_year', 'semester', '-created_at'], name='workload_di_academi_cc009b_idx')],
            },
        ),
    ]
