# Generated by Django 5.2.13 on 2026-05-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ops_admin_distribution_and_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_new_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='staff',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
