# Generated by Codex on 2026-05-05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_workloadreport_target_band_and_more'),
        ('api', '0006_staff_title_isnewemployee_notes'),
    ]

    operations = []
