# Generated by Django 5.2.13 on 2026-05-09 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_staff_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='academic_title',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='fte',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='is_new_employee',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='notes',
        ),
    ]
