# Generated by Django 5.2.13 on 2026-05-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_staff_academic_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadreport',
            name='hod_review',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
        migrations.AddField(
            model_name='workloadreport',
            name='new_staff',
            field=models.BooleanField(default=False),
        ),
    ]
