# Generated by Django 5.2.13 on 2026-05-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_hod_review_new_staff_to_workload_report'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workloadreport',
            name='workload_re_is_anom_a5b0d8_idx',
        ),
        migrations.RemoveField(
            model_name='workloadreport',
            name='is_anomaly',
        ),
    ]
