# Generated by Django 5.2.13 on 2026-05-10 04:52

from django.db import migrations, models


def backfill_confirmation_fields(apps, schema_editor):
    WorkloadReport = apps.get_model('api', 'WorkloadReport')
    AuditLog = apps.get_model('api', 'AuditLog')

    latest_logs = (
        AuditLog.objects.filter(
            changes__kind='CONFIRMATION',
            changes__confirmation='confirmed',
            report_id__isnull=False,
        )
        .order_by('report_id', '-created_at')
    )

    seen = set()
    for log in latest_logs:
        report_id = log.report_id
        if report_id in seen:
            continue
        seen.add(report_id)
        WorkloadReport.objects.filter(report_id=report_id).update(
            confirmation_status='CONFIRMED',
            confirmation_at=log.created_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_is_anomaly_from_workload_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadreport',
            name='confirmation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workloadreport',
            name='confirmation_status',
            field=models.CharField(choices=[('UNCONFIRMED', 'Unconfirmed'), ('CONFIRMED', 'Confirmed')], default='UNCONFIRMED', max_length=20),
        ),
        migrations.RunPython(backfill_confirmation_fields, migrations.RunPython.noop),
    ]
