# Generated by Django 5.2 on 2026-05-10

from django.db import migrations, models


def backfill_distributed_at(apps, schema_editor):
    """
    Reports distributed via the old endpoint had status set to 'APPROVED' with
    an AuditLog entry where action_type='APPROVED' and changes.action='distribute'.
    Back-fill distributed_at from that log and reset status to 'INITIAL' so the
    academic→HoD workflow status is not polluted by the distribution action.
    """
    WorkloadReport = apps.get_model('api', 'WorkloadReport')
    AuditLog = apps.get_model('api', 'AuditLog')

    logs = (
        AuditLog.objects.filter(
            action_type='APPROVED',
            report_id__isnull=False,
        )
        .order_by('report_id', '-created_at')
    )

    seen = set()
    for log in logs:
        report_id = log.report_id
        if report_id in seen:
            continue
        seen.add(report_id)
        changes = log.changes or {}
        if changes.get('action') != 'distribute':
            continue
        WorkloadReport.objects.filter(
            report_id=report_id,
            status='APPROVED',
        ).update(
            distributed_at=log.created_at,
            status='INITIAL',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_workloadreport_confirmation_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadreport',
            name='distributed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_distributed_at, migrations.RunPython.noop),
    ]
