# Generated by Codex on 2026-05-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_staff_access_school_ops_api'),
        ('api', '0014_workloadreport_distributed_at'),
    ]

    operations = []
