# Generated by Django 5.2.13 on 2026-05-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_workloadreport_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadreport',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
